name: local
variables:
  - name: token
    value: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NzczNjA2MTIsImV4cCI6MTc3NzM2NDIxMiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJlbWFpbEFkZHJlc3MiOiJhZG1pbkB0b3Vybm9pLmNvbSJ9.zeo9AUlVVdmygcfUfJSTIaahaOBueh1XhgW8oOy3OTAl5H3lyMrDqubUaTPXK4rwguKyM07QMkOpwPgBGTiZ9JAwy9HfNfyi7j4HNo5-DXmuauLPJi7Jm4R106yDtvRotbsXMeY1uB44yWmRaQtiYHslxpINeehovB6KwP6DYjCXgssr0m14umsFklUpUO_I8BOXRxTz027-bHoTVzmvXDQjXAwhM59sI9AOtE2de4UjP4Gvr9ZL6rbQckWAuXJaKTkMuLBjx2PYUORkhu3xG2QQaW3on03jx5vA2ovtiJz4eDijwGAXZC1P7lPD005UyWJIYjUPI5YwDUBZ7nnqGQ
